name: ExceptionLibCICD

on:
  push:
    branches:
      - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - run: npm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN}
      - run: echo "secret ${{ secrets.NPM_ACCESS_TOKEN }}."
      - run: npm install
      - run: npm run build
      - run: npm publish --access public
      # - name: install-dependencies
      #   run: npm install
      # - name: build
      #   run: npm run build
      # - name: publish
      #   run: npm publish --access public
      - run: echo "This job's status is ${{ job.status }}."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
